name: Build releases

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: docker

    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            tool: cross
          - target: aarch64-unknown-linux-gnu
            tool: cross
          - target: x86_64-pc-windows-gnu
            tool: cross
          - target: x86_64-apple-darwin
            tool: zig
          - target: aarch64-apple-darwin
            tool: zig

    steps:
      - name: Cache Rust
        uses: actions/cache@v5
        id: cache-rust
        with:
          path: |
            ~/.cargo/bin/
            ~/.rustup/
            ~/.cargo/env
          key: ${{ runner.os }}-rust
      
      - uses: actions/checkout@v4

      - name: Install minimal Rust
        shell: bash
        run: |
          set -e
          if [ ! -x "$HOME/.cargo/bin/rustup" ]; then
          curl https://sh.rustup.rs -sSf | sh -s -- \
              -y \
              --profile minimal
          fi

      - name: Install Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Install cross
        if: matrix.tool == 'cross'
        run: cargo install cross

      - name: Install zigbuild
        if: matrix.tool == 'zig'
        run: |
          pip install ziglang
          cargo install cargo-zigbuild

      - name: Build with cross
        if: matrix.tool == 'cross'
        run: cross build --release --target ${{ matrix.target }}

      - name: Build with zigbuild
        if: matrix.tool == 'zig'
        run: cargo zigbuild --release --target ${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cli-tool-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/*