name: Update changelog

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Configure git authentication
        run: |
          git remote set-url origin \
            https://x-access-token:${{ secrets.FORGEJO_TOKEN }}@git.jonahmakowski.ca/${{ forgejo.repository }}.git

      - name: Get cache epoch (weekly)
        id: cache-epoch
        run: echo "week=$(date +%G-W%V)" >> "$GITHUB_OUTPUT"

      - name: Cache Git Cliff
        uses: actions/cache@v5
        id: git-cliff-cache
        with:
          path: |
            $HOME/.install-action/
          key: ${{ runner.os }}-git-cliff-${{ steps.cache-epoch.outputs.week }}
      
      - name: Check for git-cliff
        id: git-cliff-check
        run: |
          if "$HOME/.install-action/bin/git-cliff" --version >/dev/null 2>&1; then
            echo "installed=true" >> $FORGEJO_OUTPUT
          else
            echo "installed=false" >> $FORGEJO_OUTPUT
          fi

      - name: Install git-cliff
        if: steps.git-cliff-check.outputs.installed == 'false'
        uses: https://github.com/taiki-e/install-action@git-cliff

      - name: Add git-cliff to PATH (if from cache)
        if: steps.git-cliff-check.outputs.installed == 'true'
        run: echo "$HOME/.install-action/bin" >> $FORGEJO_ENV

      - name: Generate changelog
        run: |
          git-cliff --output CHANGELOG.md

      - name: Commit changelog
        run: |
          git config user.name "forgejo-actions"
          git config user.email "actions@localhost"

          git add CHANGELOG.md

          if git diff --cached --quiet; then
            echo "No changelog changes"
          else
            git commit -m "docs(changelog): Update changelog"
            git push
          fi